name: Windows MSVC CI

on: [pull_request]

jobs:
  windows-build-test:
    runs-on: windows-2019
    steps:
      - name: Clone and checkout commit
        uses: actions/checkout@v1
      - name: Clang-tidy existence test
        run: C:\msys64\mingw64\bin\clang-tidy --version
        continue-on-error: true
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.12.9
          host: windows
          target: desktop
          modules: qtwebengine
      - name: Download QtKeychain
        run: git clone --depth 1 -b v0.10.0 https://github.com/frankosterfeld/qtkeychain.git
      - name: Compile QtKeychain
        run: cd qtkeychain && cmake -G "Visual Studio 16 2019" -DCMAKE_PREFIX_PATH=$Env:Qt5_DIR\lib\cmake . && cmake --build . --config Release
      - name: Let CMake generate build configuration
        run: cmake -G "Visual Studio 16 2019" -DNO_SHIBBOLETH=1 -DBUILD_UPDATER=ON -DUNIT_TESTING=ON -DQTKEYCHAIN_INCLUDE_DIR=qtkeychain "-DQTKEYCHAIN_LIBRARY=qtkeychain\Release\qt5keychain.lib" .
      - name: Build
        run: cmake --build . --config Release -t SyncEngineTest
      - name: Run test
        run: bin\Release\SyncEngineTest
